/**
 * ConfigEngine — CodeWhale config.toml 安全读写引擎
 *
 * 负责读取、写入、备份 CodeWhale 的配置文件。
 * 所有写操作自动创建 .bak 备份，防止误操作导致配置丢失。
 *
 * 配置路径查找顺序：
 *   1. 显式传入的路径
 *   2. 当前工作目录下的 config.toml
 *   3. 用户主目录下的 .codewhale/config.toml
 *
 * @module config
 */

import { parse, stringify } from 'smol-toml';
import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, dirname } from 'node:path';

/**
 * @typedef {import('./types.js').ProviderConfig} ProviderConfig
 * @typedef {import('./types.js').ActiveConfig} ActiveConfig
 * @typedef {import('./types.js').SkillEntry} SkillEntry
 */

/**
 * 默认配置骨架 — 当 config.toml 不存在时使用此模板创建
 */
const DEFAULT_CONFIG = `# CodeWhale Configuration
# Generated by codewhale-tool

[model]
active_provider = ""
active_api_key = ""
active_model = ""

[skills]
enabled = true
`;

export class ConfigEngine {
  /**
   * @param {string} [configPath] - 显式指定的配置文件路径，不传则自动探测
   */
  constructor(configPath) {
    this._path = configPath || ConfigEngine.detectPath();
  }

  // ─── 路径探测 ──────────────────────────────────────────────

  /**
   * 自动探测 config.toml 位置
   * 优先级：cwd/config.toml → ~/.codewhale/config.toml
   * 项目目录优先，不污染 CodeWhale 全局配置
   * @returns {string} 配置文件完整路径
   */
  static detectPath() {
    const cwd = join(process.cwd(), 'config.toml');
    if (existsSync(cwd)) return cwd;

    const home = join(homedir(), '.codewhale', 'config.toml');
    if (existsSync(home)) return home;

    // 都不存在则创建在项目目录
    return cwd;
  }

  /**
   * 返回当前使用的配置文件路径
   * @returns {string}
   */
  get path() {
    return this._path;
  }

  // ─── 读取 ──────────────────────────────────────────────────

  /**
   * 读取完整配置对象
   * 如果文件不存在，返回默认骨架结构
   * @returns {object} 解析后的配置对象
   */
  read() {
    if (!existsSync(this._path)) {
      return parse(DEFAULT_CONFIG);
    }
    const raw = readFileSync(this._path, 'utf-8');
    return parse(raw);
  }

  /**
   * 读取原始 TOML 字符串（用于展示或调试）
   * @returns {string}
   */
  readRaw() {
    if (!existsSync(this._path)) return DEFAULT_CONFIG;
    return readFileSync(this._path, 'utf-8');
  }

  // ─── 写入 ──────────────────────────────────────────────────

  /**
   * 写入完整配置对象到文件
   * 写入前自动备份原文件为 config.toml.bak
   * @param {object} config - 完整配置对象
   */
  write(config) {
    this._backup();
    const dir = dirname(this._path);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    const toml = this._serialize(config);
    writeFileSync(this._path, toml, 'utf-8');
  }

  /**
   * 原地修改配置：读取 → 通过回调修改 → 写回
   * 这是最常用的安全写入模式
   * @param {(config: object) => object} updater - 接收当前配置对象，返回修改后的配置对象
   */
  update(updater) {
    const config = this.read();
    const updated = updater(config);
    this.write(updated);
  }

  /**
   * 备份当前配置文件为 .bak
   * @private
   */
  _backup() {
    if (existsSync(this._path)) {
      const bak = this._path + '.bak';
      copyFileSync(this._path, bak);
    }
  }

  /**
   * 序列化配置对象为 TOML 字符串，附带结构化注释
   * @param {object} config
   * @returns {string}
   * @private
   */
  _serialize(config) {
    let toml = stringify(config);
    // 添加文件头注释
    const header = '# CodeWhale Configuration\n# Managed by codewhale-tool\n# Backup: config.toml.bak\n\n';
    return header + toml;
  }

  // ─── 活动配置快捷方法（旧格式） ────────────────────────────

  /**
   * 获取当前活动的 provider / api_key / model（旧格式）
   * @returns {ActiveConfig}
   */
  getActive() {
    const cfg = this.read();
    const model = cfg.model || {};
    return {
      active_provider: model.active_provider || '',
      active_api_key: model.active_api_key || '',
      active_model: model.active_model || '',
    };
  }

  /**
   * 设置当前活动配置（旧格式）
   * @param {Partial<ActiveConfig>} active - 要更新的活动字段
   */
  setActive(active) {
    this.update((cfg) => {
      if (!cfg.model) cfg.model = {};
      if (active.active_provider !== undefined) cfg.model.active_provider = active.active_provider;
      if (active.active_api_key !== undefined) cfg.model.active_api_key = active.active_api_key;
      if (active.active_model !== undefined) cfg.model.active_model = active.active_model;
      return cfg;
    });
  }

  // ─── Provider 快捷方法 ─────────────────────────────────────

  /**
   * 获取所有 provider 配置
   * @returns {Record<string, ProviderConfig>}
   */
  getProviders() {
    const cfg = this.read();
    return cfg.providers || {};
  }

  /**
   * 设置整个 providers 配置块
   * @param {Record<string, ProviderConfig>} providers
   */
  setProviders(providers) {
    this.update((cfg) => {
      cfg.providers = providers;
      return cfg;
    });
  }

  // ─── Skill 快捷方法 ────────────────────────────────────────

  /**
   * 获取 skills 配置
   * @returns {object}
   */
  getSkills() {
    const cfg = this.read();
    return cfg.skills || { enabled: true, installed: [] };
  }

  /**
   * 设置 skills 配置
   * @param {object} skills
   */
  setSkills(skills) {
    this.update((cfg) => {
      cfg.skills = skills;
      return cfg;
    });
  }

  // ─── 模型配置（新格式） ────────────────────────────────────

  /**
   * 获取模型配置（新格式）
   * 包含：官方 API key、第三方开关、当前激活的第三方 provider
   * @returns {{official_api_key: string, use_third_party: boolean, active_provider: string}}
   */
  getModelConfig() {
    const cfg = this.read();
    const model = cfg.model || {};
    return {
      official_api_key: model.official_api_key || '',
      use_third_party: !!model.use_third_party,
      active_provider: model.active_provider || '',
    };
  }

  /**
   * 设置模型配置（部分更新）
   * @param {{official_api_key?: string, use_third_party?: boolean, active_provider?: string}} config
   */
  setModelConfig(config) {
    this.update((cfg) => {
      if (!cfg.model) cfg.model = {};
      if (config.official_api_key !== undefined) cfg.model.official_api_key = config.official_api_key;
      if (config.use_third_party !== undefined) cfg.model.use_third_party = config.use_third_party;
      if (config.active_provider !== undefined) cfg.model.active_provider = config.active_provider;
      return cfg;
    });
  }
}